version: '3.8'

services:
  postgres_nlw:
    container_name: grades
    image: postgres
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=alunos_generation